export const defaultTheme = {
  name: 'agroceo',
  roundness: 8,
  colors: {
    primary: '#02733E',
    primaryVariant: '#F39200',
    secondary: '#EA690A',
    secondaryAccent: '#F39200',
    background: '#FFFFFF',
    surface: '#F5F5F7',
    success: '#018849',
    error: '#ED1C24',
    alert: '#FFD400',
    neutral0: '#FFFFFF',
    neutral1: '#F5F5F7',
    neutral2: '#E5E5E5',
    neutral3: '#C0C0C0',
    neutral4: '#7C7B7B',
    neutral5: '#212121',
    neutral6: '#A3A3A3',
    green: '#03B562',
    darkGreen: '#013C21',
    loginImgOverlay: 'rgba(4, 241, 130, 0.7)',
    gray: '#272727',
    events: {
      onPrimary: '#FFFFFF',
      onPrimaryVariant: '#FFFFFF',
      onSecondary: '#FFFFFF',
      onSecondaryAccent: '#FFFFFF',
      onBackground: '#212121',
      onSurface: '#212121',
      onSuccess: '#FFFFFF',
      onError: '#FFFFFF',
      onAlert: '#212121',
      onNeutral0: '#212121',
      onNeutral1: '#212121',
      onNeutral2: '#212121',
      onNeutral3: '#212121',
      onNeutral4: '#FFFFFF',
      onNeutral5: '#FFFFFF',
    },
  },
  text: {
    size: {
      h1: '96px',
      h2: '64px',
      h3: '48px',
      h4: '32px',
      h5: '24px',
      large: '18px',
      medium: '16px',
      normal: '14px',
      small: '13px',
      caption: '12px',
      extraSmall: '11px',
      mini: '10px',
      label: '7px',
    },
    type: {
      lineThrough: 'line-through',
      underline: 'underline',
    },
    fontFamily: {
      bold: 'Inter-Bold',
      regular: 'Inter-Regular',
    },
    weight: {
      thin: 200,
      normal: 400,
      bold: 700,
    },
  },
  fonts: {
    regular: 'Inter-Regular'
  },
  animation: {
    scale: 1.0
  },
  borderRadius: {
    sm: '2px',
    md: '5px',
    lg: '10px',
    xl1: '20px',
    xl2: '10em',
  },
  padding: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    exg: '50px',
  },
  margin: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    large: '20px',
    xg: '24px',
  },
  opacity: {
    low: '.9',
    medium: '.5',
    high: '.2',
  },
  border: {
    buttonSuccess: `2px solid #005500`,
    buttonError: `2px solid #550000`,
    header: `1px solid #EBEBEB`,
  },
  align: {
    center: 'center',
    spaceAround: 'space-around',
    spaceBetween: 'space-between',
    flexEnd: 'flex-end',
  },
};
